export const emojiTagMap: { [key: string]: string } = {
  "Speedrun": "⏱️",
  "Strategy": "🧠",
  "Co-op": "🤝",
  "Teamplay": "🤝",
  "Creative": "🛠️",
  "Sandbox Games": "🧱",
  "RPG": "⚔️",
  "Platformer": "🌀",
  "Builder": "🏗️",
  "Leadership": "👑",
  "Communication": "🗣️",
  "Focus Training": "🧘",
  "Meta Mastery": "📊",
  "Support": "🛡️",
  "Tilt": "😤",
  "Aim": "🎯",
  "Tilt Control": "🎮",
  "Role Optimization": "🧬",
  "Stealth": "🕶️",
  "Esports Prep": "🏁",
  "World Design": "🌍",
  "Performance Under Pressure": "🔥"
};